version: '2'

services:

  base:
    image: node:11
    volumes:
      - .:/usr/src/service/
      - node_modules:/usr/src/service/node_modules
    working_dir: /usr/src/service/

  install:
    extends:
      service: base
    command: npm i

  storybook-install:
    extends:
      service: base
    command: npx -p @storybook/cli sb init

  story:
    extends:
      service: base
    command: yarn run storybook
    ports:
      - 9009:9009

  build:
    extends:
      service: base
    command: npm run build

  create-bundles:
    extends:
      service: base
    command: npm run create-bundles

volumes:
  node_modules: